services:
  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

volumes:
  postgres-data-volume:
    name: postgres-data-volume
    driver: local